name: f001_receipt_printing
description: A Flutter plugin to connect to a Bluetooth printer device, and print data as an image.
version: 2.2.2
homepage: https://github.com/Accountsoft-Innovation/f001_receipt_printing

environment:
  sdk: ^3.3.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.8
  esc_pos_utils_plus: ^2.0.4
  flutter_blue_classic: ^0.0.5

  # For capturing widgets as images
  screenshot: ^3.0.0
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: plugin.aisb.f001_receipt_printing
        pluginClass: F001ReceiptPrintingPlugin
      ios:
        pluginClass: F001ReceiptPrintingPlugin
